name: tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - '**.md'
      - '**.rst'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - '**.md'
      - '**.rst'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: [
            '3.9',
            '3.10',
            '3.11',
            '3.12',
            '3.13'
            # pypy3  # didn't build on CI anymore, happy for help: https://github.com/mthh/routingpy/issues/60
        ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        cache: pip

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install dependencies
      run: |
        pip install -r requirements_dev.txt

    - name: style & lint checks
      run: |
        pre-commit run --all-files --color=always

    - name: pytest and coverage
      run: |
        pip install -e .
        coverage run --source=routingpy --module pytest
        coverage lcov --include "routingpy/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
