name: Publish wheels

on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "*"

jobs:
  build_wheels:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build Wheels
        run: |
          pip install -r requirements_dev.txt
          python -m build --wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl

  upload_all:
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: mthh
          password: ${{ secrets.PYPI_PASS }}
